name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform fmt
        run: terraform fmt -check 
        working-directory: ${{ github.workspace }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ github.workspace }}

      - name: Terraform plan
        run: terraform plan
        working-directory: ${{ github.workspace }}

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.workspace }}
